/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmarks implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String url;
    private final String title;
    private final Long createdBy;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;

    public Bookmarks(Bookmarks value) {
        this.id = value.id;
        this.url = value.url;
        this.title = value.title;
        this.createdBy = value.createdBy;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Bookmarks(
        Long id,
        String url,
        String title,
        Long createdBy,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.url = url;
        this.title = title;
        this.createdBy = createdBy;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.bookmarks.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.bookmarks.url</code>.
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * Getter for <code>public.bookmarks.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>public.bookmarks.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Getter for <code>public.bookmarks.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.bookmarks.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Bookmarks (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(title);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
