/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarkTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long bookmarkId;
    private final Long tagId;

    public BookmarkTag(BookmarkTag value) {
        this.bookmarkId = value.bookmarkId;
        this.tagId = value.tagId;
    }

    public BookmarkTag(
        Long bookmarkId,
        Long tagId
    ) {
        this.bookmarkId = bookmarkId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>public.bookmark_tag.bookmark_id</code>.
     */
    public Long getBookmarkId() {
        return this.bookmarkId;
    }

    /**
     * Getter for <code>public.bookmark_tag.tag_id</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookmarkTag (");

        sb.append(bookmarkId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
