/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqBookmarkTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long bookmarkId;
    private Long tagId;

    public JooqBookmarkTag() {}

    public JooqBookmarkTag(JooqBookmarkTag value) {
        this.bookmarkId = value.bookmarkId;
        this.tagId = value.tagId;
    }

    public JooqBookmarkTag(
        Long bookmarkId,
        Long tagId
    ) {
        this.bookmarkId = bookmarkId;
        this.tagId = tagId;
    }

    /**
     * Getter for <code>BOOKMARK_TAG.BOOKMARK_ID</code>.
     */
    public Long getBookmarkId() {
        return this.bookmarkId;
    }

    /**
     * Setter for <code>BOOKMARK_TAG.BOOKMARK_ID</code>.
     */
    public void setBookmarkId(Long bookmarkId) {
        this.bookmarkId = bookmarkId;
    }

    /**
     * Getter for <code>BOOKMARK_TAG.TAG_ID</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>BOOKMARK_TAG.TAG_ID</code>.
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqBookmarkTag other = (JooqBookmarkTag) obj;
        if (this.bookmarkId == null) {
            if (other.bookmarkId != null)
                return false;
        }
        else if (!this.bookmarkId.equals(other.bookmarkId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.bookmarkId == null) ? 0 : this.bookmarkId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqBookmarkTag (");

        sb.append(bookmarkId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
