/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.Addresses;
import com.sivalabs.bookmarks.jooq.tables.BookmarkTag;
import com.sivalabs.bookmarks.jooq.tables.Bookmarks;
import com.sivalabs.bookmarks.jooq.tables.Tags;
import com.sivalabs.bookmarks.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>ADDRESSES</code>.
     */
    public final Addresses ADDRESSES = Addresses.ADDRESSES;

    /**
     * The table <code>BOOKMARK_TAG</code>.
     */
    public final BookmarkTag BOOKMARK_TAG = BookmarkTag.BOOKMARK_TAG;

    /**
     * The table <code>BOOKMARKS</code>.
     */
    public final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>TAGS</code>.
     */
    public final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>USERS</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.ADDRESS_ID_SEQ,
            Sequences.BOOKMARK_ID_SEQ,
            Sequences.TAG_ID_SEQ,
            Sequences.USER_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Addresses.ADDRESSES,
            BookmarkTag.BOOKMARK_TAG,
            Bookmarks.BOOKMARKS,
            Tags.TAGS,
            Users.USERS
        );
    }
}
