/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>ADDRESS_ID_SEQ</code>
     */
    public static final Sequence<Long> ADDRESS_ID_SEQ = Internal.createSequence("ADDRESS_ID_SEQ", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>BOOKMARK_ID_SEQ</code>
     */
    public static final Sequence<Long> BOOKMARK_ID_SEQ = Internal.createSequence("BOOKMARK_ID_SEQ", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>TAG_ID_SEQ</code>
     */
    public static final Sequence<Long> TAG_ID_SEQ = Internal.createSequence("TAG_ID_SEQ", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);

    /**
     * The sequence <code>USER_ID_SEQ</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = Internal.createSequence("USER_ID_SEQ", DefaultSchema.DEFAULT_SCHEMA, SQLDataType.BIGINT, null, null, null, null, false, null);
}
