/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.address_id_seq</code>
     */
    public static final Sequence<Long> ADDRESS_ID_SEQ = Internal.createSequence("address_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.bookmark_id_seq</code>
     */
    public static final Sequence<Long> BOOKMARK_ID_SEQ = Internal.createSequence("bookmark_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.tag_id_seq</code>
     */
    public static final Sequence<Long> TAG_ID_SEQ = Internal.createSequence("tag_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Long> USER_ID_SEQ = Internal.createSequence("user_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
