/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq;


import com.sivalabs.bookmarks.jooq.tables.Addresses;
import com.sivalabs.bookmarks.jooq.tables.BookmarkTag;
import com.sivalabs.bookmarks.jooq.tables.Bookmarks;
import com.sivalabs.bookmarks.jooq.tables.Tags;
import com.sivalabs.bookmarks.jooq.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ADDRESSES</code>.
     */
    public static final Addresses ADDRESSES = Addresses.ADDRESSES;

    /**
     * The table <code>BOOKMARK_TAG</code>.
     */
    public static final BookmarkTag BOOKMARK_TAG = BookmarkTag.BOOKMARK_TAG;

    /**
     * The table <code>BOOKMARKS</code>.
     */
    public static final Bookmarks BOOKMARKS = Bookmarks.BOOKMARKS;

    /**
     * The table <code>TAGS</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>USERS</code>.
     */
    public static final Users USERS = Users.USERS;
}
