/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.Bookmarks;
import com.sivalabs.bookmarks.jooq.tables.pojos.JooqBookmarks;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarksRecord extends UpdatableRecordImpl<BookmarksRecord> implements Record6<Long, String, String, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bookmarks.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bookmarks.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bookmarks.url</code>.
     */
    public void setUrl(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bookmarks.url</code>.
     */
    public String getUrl() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bookmarks.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.bookmarks.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bookmarks.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.bookmarks.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.bookmarks.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.bookmarks.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.bookmarks.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.bookmarks.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Bookmarks.BOOKMARKS.ID;
    }

    @Override
    public Field<String> field2() {
        return Bookmarks.BOOKMARKS.URL;
    }

    @Override
    public Field<String> field3() {
        return Bookmarks.BOOKMARKS.TITLE;
    }

    @Override
    public Field<Long> field4() {
        return Bookmarks.BOOKMARKS.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Bookmarks.BOOKMARKS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Bookmarks.BOOKMARKS.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUrl();
    }

    @Override
    public String component3() {
        return getTitle();
    }

    @Override
    public Long component4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUrl();
    }

    @Override
    public String value3() {
        return getTitle();
    }

    @Override
    public Long value4() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public BookmarksRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public BookmarksRecord value2(String value) {
        setUrl(value);
        return this;
    }

    @Override
    public BookmarksRecord value3(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public BookmarksRecord value4(Long value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public BookmarksRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BookmarksRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public BookmarksRecord values(Long value1, String value2, String value3, Long value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookmarksRecord
     */
    public BookmarksRecord() {
        super(Bookmarks.BOOKMARKS);
    }

    /**
     * Create a detached, initialised BookmarksRecord
     */
    public BookmarksRecord(Long id, String url, String title, Long createdBy, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Bookmarks.BOOKMARKS);

        setId(id);
        setUrl(url);
        setTitle(title);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BookmarksRecord
     */
    public BookmarksRecord(JooqBookmarks value) {
        super(Bookmarks.BOOKMARKS);

        if (value != null) {
            setId(value.getId());
            setUrl(value.getUrl());
            setTitle(value.getTitle());
            setCreatedBy(value.getCreatedBy());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
