/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables.records;


import com.sivalabs.bookmarks.jooq.tables.BookmarkTag;
import com.sivalabs.bookmarks.jooq.tables.pojos.JooqBookmarkTag;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarkTagRecord extends TableRecordImpl<BookmarkTagRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.bookmark_tag.bookmark_id</code>.
     */
    public void setBookmarkId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bookmark_tag.bookmark_id</code>.
     */
    public Long getBookmarkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bookmark_tag.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bookmark_tag.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return BookmarkTag.BOOKMARK_TAG.BOOKMARK_ID;
    }

    @Override
    public Field<Long> field2() {
        return BookmarkTag.BOOKMARK_TAG.TAG_ID;
    }

    @Override
    public Long component1() {
        return getBookmarkId();
    }

    @Override
    public Long component2() {
        return getTagId();
    }

    @Override
    public Long value1() {
        return getBookmarkId();
    }

    @Override
    public Long value2() {
        return getTagId();
    }

    @Override
    public BookmarkTagRecord value1(Long value) {
        setBookmarkId(value);
        return this;
    }

    @Override
    public BookmarkTagRecord value2(Long value) {
        setTagId(value);
        return this;
    }

    @Override
    public BookmarkTagRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookmarkTagRecord
     */
    public BookmarkTagRecord() {
        super(BookmarkTag.BOOKMARK_TAG);
    }

    /**
     * Create a detached, initialised BookmarkTagRecord
     */
    public BookmarkTagRecord(Long bookmarkId, Long tagId) {
        super(BookmarkTag.BOOKMARK_TAG);

        setBookmarkId(bookmarkId);
        setTagId(tagId);
    }

    /**
     * Create a detached, initialised BookmarkTagRecord
     */
    public BookmarkTagRecord(JooqBookmarkTag value) {
        super(BookmarkTag.BOOKMARK_TAG);

        if (value != null) {
            setBookmarkId(value.getBookmarkId());
            setTagId(value.getTagId());
        }
    }
}
