/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.bookmarks.jooq.tables;


import com.sivalabs.bookmarks.jooq.DefaultSchema;
import com.sivalabs.bookmarks.jooq.Keys;
import com.sivalabs.bookmarks.jooq.tables.records.AddressesRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Addresses extends TableImpl<AddressesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ADDRESSES</code>
     */
    public static final Addresses ADDRESSES = new Addresses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressesRecord> getRecordType() {
        return AddressesRecord.class;
    }

    /**
     * The column <code>ADDRESSES.ID</code>.
     */
    public final TableField<AddressesRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field("NEXT VALUE FOR \"PUBLIC\".\"ADDRESS_ID_SEQ\"", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>ADDRESSES.STREET</code>.
     */
    public final TableField<AddressesRecord, String> STREET = createField(DSL.name("STREET"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>ADDRESSES.CITY</code>.
     */
    public final TableField<AddressesRecord, String> CITY = createField(DSL.name("CITY"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>ADDRESSES.STATE</code>.
     */
    public final TableField<AddressesRecord, String> STATE = createField(DSL.name("STATE"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>ADDRESSES.ZIP</code>.
     */
    public final TableField<AddressesRecord, String> ZIP = createField(DSL.name("ZIP"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>ADDRESSES.COUNTRY</code>.
     */
    public final TableField<AddressesRecord, String> COUNTRY = createField(DSL.name("COUNTRY"), SQLDataType.VARCHAR(20), this, "");

    private Addresses(Name alias, Table<AddressesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Addresses(Name alias, Table<AddressesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ADDRESSES</code> table reference
     */
    public Addresses(String alias) {
        this(DSL.name(alias), ADDRESSES);
    }

    /**
     * Create an aliased <code>ADDRESSES</code> table reference
     */
    public Addresses(Name alias) {
        this(alias, ADDRESSES);
    }

    /**
     * Create a <code>ADDRESSES</code> table reference
     */
    public Addresses() {
        this(DSL.name("ADDRESSES"), null);
    }

    public <O extends Record> Addresses(Table<O> child, ForeignKey<O, AddressesRecord> key) {
        super(child, key, ADDRESSES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<AddressesRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    public Addresses as(String alias) {
        return new Addresses(DSL.name(alias), this);
    }

    @Override
    public Addresses as(Name alias) {
        return new Addresses(alias, this);
    }

    @Override
    public Addresses as(Table<?> alias) {
        return new Addresses(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Addresses rename(String name) {
        return new Addresses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Addresses rename(Name name) {
        return new Addresses(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Addresses rename(Table<?> name) {
        return new Addresses(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
