name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: [ 'temurin' ]
        java: [ '17' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.java }} (${{ matrix.distribution }})
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
          cache: 'maven'

      - name: Build with Gradle
        run: ./gradlew build
